COMPUTED VALUES:
affinity: {}
annotations: {}
args:
- --workdir=/fluent-bit/etc
- --config=/fluent-bit/etc/conf/fluent-bit.conf
autoscaling:
  behavior: {}
  customRules: []
  enabled: false
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 75
  vpa:
    annotations: {}
    controlledResources: []
    controlledValues: null
    enabled: false
    maxAllowed: {}
    minAllowed: {}
    recommender: default
    updatePolicy:
      updateMode: Auto
backend:
  type: es
command:
- /fluent-bit/bin/fluent-bit
config:
  customParsers: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  extraFiles: {}
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        Kube_Tag_Prefix     kube.var.log.containers.
  inputs: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            cri
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
  outputs: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            mhc-logging-master
        Port            9200
        HTTP_User       elastic
        HTTP_Passwd     y42z3fhQ8nkuUaYX
        tls             On
        tls.verify      Off
        Logstash_Format On
        Retry_Limit     False
  service: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        Off
        Parsers_File  parsers.conf
  upstream: {}
daemonSetVolumeMounts:
- mountPath: /var/log
  name: varlog
- mountPath: /var/lib/docker/containers
  name: varlibdockercontainers
  readOnly: true
- mountPath: /etc/machine-id
  name: etcmachineid
  readOnly: true
daemonSetVolumes:
- hostPath:
    path: /var/log
  name: varlog
- hostPath:
    path: /var/lib/docker/containers
  name: varlibdockercontainers
- hostPath:
    path: /etc/machine-id
    type: File
  name: etcmachineid
dashboards:
  annotations: {}
  deterministicUid: false
  enabled: false
  labelKey: grafana_dashboard
  labelValue: 1
  namespace: ""
dnsConfig: {}
dnsPolicy: ClusterFirst
env: []
envFrom: []
envWithTpl: []
existingConfigMap: ""
extraContainers: []
extraPorts: []
extraVolumeMounts: []
extraVolumes: []
flush: 1
fullnameOverride: ""
hostAliases: []
hostNetwork: false
hotReload:
  enabled: false
  extraWatchVolumes: []
  image:
    digest: null
    pullPolicy: IfNotPresent
    repository: ghcr.io/jimmidyson/configmap-reload
    tag: v0.15.0
  resources: {}
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
image:
  digest: null
  pullPolicy: IfNotPresent
  repository: cr.fluentbit.io/fluent/fluent-bit
  tag: null
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  extraHosts: []
  hosts: []
  ingressClassName: ""
  tls: []
initContainers: []
kind: DaemonSet
labels: {}
lifecycle: {}
livenessProbe:
  httpGet:
    path: /
    port: http
logLevel: info
luaScripts: {}
metricsPort: 2020
minReadySeconds: null
nameOverride: ""
networkPolicy:
  enabled: false
nodeSelector: {}
openShift:
  enabled: false
  securityContextConstraints:
    annotations: {}
    create: true
    existingName: ""
    name: ""
    runAsUser:
      type: RunAsAny
    seLinuxContext:
      type: MustRunAs
podAnnotations: {}
podDisruptionBudget:
  annotations: {}
  enabled: false
  maxUnavailable: 30%
podLabels: {}
podSecurityContext: {}
podSecurityPolicy:
  annotations: {}
  create: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
priorityClassName: ""
prometheusRule:
  enabled: false
rbac:
  create: true
  eventsAccess: false
  nodeAccess: false
readinessProbe:
  httpGet:
    path: /api/v2/health
    port: http
replicaCount: 1
resources: {}
securityContext: {}
service:
  annotations: {}
  externalIPs: []
  internalTrafficPolicy: null
  labels: {}
  loadBalancerClass: null
  loadBalancerIP: null
  loadBalancerSourceRanges: []
  port: 2020
  type: ClusterIP
serviceAccount:
  annotations: {}
  automountServiceAccountToken: null
  create: true
  name: null
serviceMonitor:
  additionalEndpoints: []
  enabled: false
terminationGracePeriodSeconds: null
testFramework:
  enabled: true
  image:
    digest: null
    pullPolicy: Always
    repository: busybox
    tag: latest
  namespace: null
tolerations:
- operator: Exists
updateStrategy: {}
volumeMounts:
- mountPath: /fluent-bit/etc/conf
  name: config
