#
# MHC DEV Logs
#
[OUTPUT]
    Name                es
    Match               kube.*
    Host                mhc-logging-master
    Port                9200
    HTTP_User           elastic
    HTTP_Passwd         Elastic@123

    tls                 On
    tls.verify          Off

    Logstash_Format     On
    Logstash_Prefix     mhc-dev

    Retry_Limit         False

    Include_Tag_Key     On
    Tag_Key             fluentbit_tag
